---
title: "Part 2: Data Cleaning and Descriptive Checks"
author: "Anonymous"
format:
  html:
    callout-appearance: simple
    reference-location: margin
    embed-resources: true
---

```{r}
#| echo: false
#| output: false
#| label: setup

library(tidyverse)
library(ggplot2)
library(sgt)
library(numDeriv)
library(ggdist)
# setting the theme
theme_set(theme_minimal())
# model
library(brms)
# plot results
library(tidybayes)
library(here)
```

# Set up

Read in response data

```{r}
#| code-fold: true
raw_df <- read_csv(here::here("data", "part2", "exp2-pilot.csv")) %>%
  as_tibble(.) %>%
  filter(status != "rejected")

pilot_df <- raw_df %>% filter(responseId != "windowEvents")
```

# Eye distance to screen 

TODO

# Correlation for the `ProjToAxis` task

TODO

# Timing

On average, how long did people take? 

```{r}
#| code-fold: true
pilot_df %>%
  # no need for introduction
  filter(trialOrder >= 3, trialOrder <= 72) %>%
  group_by(participantId, trialOrder, cleanedDuration) %>%
  summarise(.) %>%
  group_by(participantId) %>%
  summarise(sum_cleanedDuration = sum(cleanedDuration)) %>%
  mutate(totalDuration = sum_cleanedDuration / (1000 * 60))
```

So the average across participants is ... 

```{r}
#| code-fold: true
pilot_df %>%
  # no need for introduction
  filter(trialOrder >= 3, trialOrder <= 72) %>%
  group_by(participantId, trialOrder, cleanedDuration) %>%
  summarise(.) %>%
  group_by(participantId) %>%
  summarise(sum_cleanedDuration = sum(cleanedDuration)) %>%
  mutate(totalDuration = sum_cleanedDuration / (1000 * 60)) %>%
  pull(totalDuration) %>%
  mean(.)
```

What about demographics? 

```{r}
#| code-fold: true
pilot_df %>%
  filter(trialId == "post_study") %>%
  select(participantId, responseId, answer) %>%
  pivot_wider(names_from = responseId, values_from = answer) %>%
  select(-`gender-other`, -`feedback-text`) %>%
  ggplot(aes(x = age, y = gender)) +
  geom_dotplot()
```

Gender is balanced: 

```{r}
#| code-fold: true
pilot_df %>%
  filter(trialId == "post_study") %>%
  select(participantId, responseId, answer) %>%
  pivot_wider(names_from = responseId, values_from = answer) %>%
  select(-`gender-other`, -`feedback-text`) %>%
  count(gender)
```

Mean age is 38. 

```{r}
#| code-fold: true
pilot_df %>%
  filter(trialId == "post_study") %>%
  select(participantId, responseId, answer) %>%
  pivot_wider(names_from = responseId, values_from = answer) %>%
  select(-`gender-other`, -`feedback-text`) %>%
  mutate(age = as.numeric(age)) %>%
  pull(age) %>%
  mean(.)
```

4 our of 20 people provided textual feedback; similar to the ones that Moritz et al. obtained. 